### ISSUE TITLE
Decryptorのハリボテ作成

### ISSUE THREAD

**Issue by iihiro** [iihiro/FHE-Table-Search#1]
* DecServerのハリボテ実装
  * 基本設計書:3.2.1
  * 参考実装: https://github.com/iihiro/prv_cmp/tree/work/multi-node/prvc/prvc_dec
* DECClientの実装
  * 基本設計書:3.1.1
  * 参考実装: https://github.com/iihiro/prv_cmp/blob/work/multi-node/prvc/prvc_enc/prvc_enc_dec_client.cpp
* 動作確認

**Comment by YHSHHsaiko** [comment]
-----
## やったこと
### `fts_server`
* 参考実装をもとに`DecServer`クラスを作成
* `state`については，`StateInit`のみ仮で作成
* `callback`は，
  - 仮の`CallbackParam`(変数`int32_t dummy`のみを保持)を定義
  - 新しい鍵リクエスト用の`CallbackFunctionForNewKeys`コールバックを定義
  - 結果リクエスト用の`CallbackFunctionForResultRequest`コールバックを定義
  - 現時点では，ログを出力するだけ

### `fts_client`
* 参考実装をもとに`DecClient`クラスを作成
  - 現時点では，`new_keys`，`delete_keys`関数はログを出力するだけ

### `fts_share`
* `ControlCode_t`を定義
* 何もしない`PubKey`クラスと`SecKey`クラスを仮で作成

-----
## テスト
* `demo`フォルダに仮プログラムを書いて，実行
### `dec`
![demo_dec](https://user-images.githubusercontent.com/44924356/87147693-062c7700-c2e8-11ea-9054-ba35eb5f3ee6.jpg)
### `user`
![demo_user](https://user-images.githubusercontent.com/44924356/87147703-0a589480-c2e8-11ea-9554-0af02a381f6b.jpg)
