### ISSUE TITLE
ComputationServerのハリボテ作成

### ISSUE THREAD

**Issue by iihiro** [iihiro/FHE-Table-Search#2]
* CSServerのハリボテ実装
  * 基本設計書: 3.3.1
  * 参考実装: https://github.com/iihiro/prv_cmp/tree/work/multi-node/prvc/prvc_eval
* CSClientの実装
  * 基本設計書: 3.1.1
  * https://github.com/iihiro/prv_cmp/blob/work/multi-node/prvc/prvc_enc/prvc_enc_eval_client.cpp
* 動作確認

**Comment by NakamRay** [comment]
@iihiro @YHSHHsaiko 
`work/issue2-cs_demo`ブランチにComputationServerのハリボテを作成してみたものをコミットしました．ご確認よろしくお願い致します．

`work/issue1-decryptor_demo`からブランチを作成して作業を行いました．

### やったこと
- UserからComputationServerへ空のクエリを送信
  - `fts_user_cs_client.cpp`の`send_query()`を実行
  - 最初に`CallbackFunctionForComputeRequest`で空のクエリを送信．このときにQueryIDとして仮に1111を設定
  - 次に`CallbackFunctionForQueryID`でQueryIDの1111をサーバーから返す
  - 受け取ったQueryID 1111を結果として表示
- Userから結果のリクエストを送信
  - 仮に1(true)を返す

### サーバのログ
```
$ ./demo/cs/cs
Launched User demo app.
State: Connected
Launched CS server [port]: 10001
[starting fts_cs server]
* done * [starting fts_cs server]
hit any key to exit server:
Listen socket.
Received compute request.
Called request_function
State: Ready
Received query request.
Received result request.
Socket closed : Sock Error Code (0)
Failed to server process (Socket closed)
```

### ユーザのログ
```
$ ./demo/user/user
Launched User demo app.
Connected to Computation Server.
sent the query
result [1111]
recieved results
result [1]
```
